# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
# highlighter : pygments
highlighter: rouge

# SEO settings
title: Dev UMBJM
description: "We write some code for fun!"
keywords: "Development, code, umbjm, universitas muhammadiyah banjarmasin, Informatika, developer,  banjarmasin"

# Site settings
url: http://umbjm.github.io
baseurl: "/"
# baseurl: ""

# Author settings
author:
  name      : Fernando Moreira
  job       : Frontend Engineer
  bio       : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb     : /images/author.jpg
  email     : nandomoreira.me@gmail.com
  url       : http://umbjm.github.io
  github    : http://github.com/umbjm


# google_analytics: UA-52446115-1
repo: http://github.com/umbjm/umbjm.github.io

# comments
disqus_shortname: "fernandomoreira"
